// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5T-Vxr-RBYg_IUtMVykl15qbeI2xd3I0',
    appId: '1:370984242246:web:8f03f1980a1e1ba5eb0e47',
    messagingSenderId: '370984242246',
    projectId: 'smartapp-1ea0b',
    authDomain: 'smartapp-1ea0b.firebaseapp.com',
    databaseURL: 'https://smartapp-1ea0b-default-rtdb.firebaseio.com',
    storageBucket: 'smartapp-1ea0b.firebasestorage.app',
    measurementId: 'G-HD1680XDFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVf95JZvo_zRGaHHJtaR0nnpotBJH77U4',
    appId: '1:370984242246:android:0843cf7a35a3c221eb0e47',
    messagingSenderId: '370984242246',
    projectId: 'smartapp-1ea0b',
    databaseURL: 'https://smartapp-1ea0b-default-rtdb.firebaseio.com',
    storageBucket: 'smartapp-1ea0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk0xSrR-KTz2Al4dtVyJ-wsMqDmmlf4eU',
    appId: '1:370984242246:ios:0e48be8c9d093fdbeb0e47',
    messagingSenderId: '370984242246',
    projectId: 'smartapp-1ea0b',
    databaseURL: 'https://smartapp-1ea0b-default-rtdb.firebaseio.com',
    storageBucket: 'smartapp-1ea0b.firebasestorage.app',
    iosClientId: '370984242246-1en2cg7ud4302r1mk2r4541eu4khp6q3.apps.googleusercontent.com',
    iosBundleId: 'com.bouizergane.smartAppBouizergane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk0xSrR-KTz2Al4dtVyJ-wsMqDmmlf4eU',
    appId: '1:370984242246:ios:0e48be8c9d093fdbeb0e47',
    messagingSenderId: '370984242246',
    projectId: 'smartapp-1ea0b',
    databaseURL: 'https://smartapp-1ea0b-default-rtdb.firebaseio.com',
    storageBucket: 'smartapp-1ea0b.firebasestorage.app',
    iosClientId: '370984242246-1en2cg7ud4302r1mk2r4541eu4khp6q3.apps.googleusercontent.com',
    iosBundleId: 'com.bouizergane.smartAppBouizergane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5T-Vxr-RBYg_IUtMVykl15qbeI2xd3I0',
    appId: '1:370984242246:web:d211b4de4c5b65e1eb0e47',
    messagingSenderId: '370984242246',
    projectId: 'smartapp-1ea0b',
    authDomain: 'smartapp-1ea0b.firebaseapp.com',
    databaseURL: 'https://smartapp-1ea0b-default-rtdb.firebaseio.com',
    storageBucket: 'smartapp-1ea0b.firebasestorage.app',
    measurementId: 'G-05V4FEM8ZR',
  );
}
